# Las tres imágenes que forman el replicaSet de mongo
mongo3:
  hostname: mongo3
  image: mongo:3.0.6
  entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles", "--rest" ]
  ports:
    - "27018:27017"
    - "28018:28017"
  restart: always

mongo2:
  hostname: mongo2
  image: mongo:3.0.6
  entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles", "--rest" ]
  ports:
    - "27019:27017"
    - "28019:28017"
  restart: always

mongo1:
  hostname: mongo1
  image: mongo:3.0.6
  entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles", "--rest" ]
  ports:
    - "27017:27017"
    - "28017:28017"
  links:
    - mongo2:mongo2
    - mongo3:mongo3
  restart: always

#La imagen de elasticsearch
elasticsearch:
  hostname: elasticsearch
  image: stabenfeldt/elasticsearch-marvel
  ports:
    - "9200:9200"
    - "9300:9300"
  links:
    - mongo1:mongo1
    - mongo2:mongo2
    - mongo3:mongo3
  volumes:
    - ./elasticsearch/logging.yml:/etc/elasticsearch/logging.yml
  restart: always

# This configures the MongoDB replicaset
mongosetup:
  image: mongo:3.0.6
  links:
    - mongo1:mongo1
    - mongo2:mongo2
    - mongo3:mongo3
  volumes:
    - ./scripts:/scripts
  entrypoint: [ "/scripts/setup.sh" ]

#Este es el componente que sincroniza mongo con elasticsearch
#El script (/transporter/run.sh) sólo inicializa
transporter:
  image: golang:1.5
  links:
    - mongo1:mongo1
    - mongo2:mongo2
    - mongo3:mongo3
    - elasticsearch:elasticsearch
  volumes:
    - ./transporter:/transporter
    - ./scripts:/scripts
  entrypoint: [ "/transporter/run.sh" ]
  restart: always


# Make sure ES does not rellocate it's shards when it has low disk space.
disabledisktreshold:
  image: mongo:3.0.6
  links:
    - elasticsearch:elasticsearch
  volumes:
    - ./scripts:/scripts
  entrypoint: [ "/scripts/disable-disk-treshold.sh" ]

# Verify reading and writing
# Run 'docker logs -f elasticmongo_verify_1' to see what it outputs.
verify:
  image: mongo:3.0.6
  links:
    - mongo1:mongo1
    - mongo2:mongo2
    - mongo3:mongo3
    - elasticsearch:elasticsearch
  volumes:
    - ./scripts:/scripts
  entrypoint: [ "/scripts/query.sh" ]
